apgsga-it/jenkins-patch-scripts

vars/patchfunctions.groovy

Nothing big, just to quickly look at the modification ... 
Basically, if apscli return anything else than 0 (when retrieveing and saving revision), we put the pipeline into error.

Putting pipeline into error if apscli return anything else than 0 when saving and retrieving revision

---

src/main/jenkins/server/testParallelBuilds.groovy
vars/patchfunctions.groovy

Concurrent Build support & a test Pipeline to test the concurrent Build Process isolated.
Parallel Buildsupport has been added to [https://github.com/apgsga-it/jenkins-patch-scripts/blob/master/vars/patchfunctions.groovy](url) , look for buildAndReleaseModulesConcurrent. 
I have added it additionally to the sequential Build process, so we always have a fallback.
Currently the buildAndReleaseModulesConcurrent is only invoked from /jenkins-patch-scripts/src/main/jenkins/server/testParallelBuilds.groovy

Che javamig 405 parallel builds

---

vars/patchDeployment.groovy

Before starting the Docker (Jadas) installation, we check that either:
- We have at least one Java Artefact.
- We have at least one DB Module.
- We force an installation from an empty patch.
Do you see the pipeline modification differently?

install Jadas docker only under some conditions.

---

vars/patchfunctions.groovy

This address the last question of https://jira.apgsga.ch/browse/JAVA8MIG-432 ... where we need to work with SNAPSHOT after a Clone, if the PROD target has never been patched.

After a Clone, if no PROD revision exists, use SNAPSHOT

---

src/main/jenkins/server/clone/reinstallPatchAfterClonePipeline.groovy

A quick one, probably more just for information.
As discussed, after a clone. when we re-install patched which were in "Informatiktest" status, the clone should tolerate that a patch file doesn't exist -> it simply means that this particular patch is managed by the "old patch system".

Tolerate that a patch file doesn't exist.

---

vars/patchfunctions.groovy

To keep things simple i build a runtime condition depending on a Environment Variable to force the failure for a Pipeline execution.
I could have provided the same Parameter on the Rest API, but that would effect the all the endpoints and clients involved (cli, rest api patch service , jenkins pipeline) .  I decided against this for the moment. 
The drawback is that, also intended failures can be provoked, for example more then one testing at the same time.

Testing restart

---

src/main/jenkins/server/patchProdPipeline.groovy
src/test/groovy/closureTests.groovy
vars/patchfunctions.groovy

I  changed the Redo Logic quite a bit. 
Now the redo logic is encapsulated in the new patchfunctions.stage function, which acutally abstracts the Stages. 
This is function is called by the mainline , with the corresponding "logic" passed as closure, 
The stages before are'nt "replayed" but skipped. The stage of the corresponding "Redo" State is redone and from then the Patch Pipeline is processed "normally".
@apgsga-jhe  FYI, i going ahead with mergeing and testing, i am terriblly curious, if this works ;-)

Redesign Redo 

---

build.gradle
gradle.properties

The Artifactory Read-only User Password is available as Environment Variable: REPO_RO_PASSWD, instead of property value. It is evaluated at Build time resp. Runtime . Developers need to add this Variable to their enviroments.
In Jenkins it is configured as "Globale Eigentschaft", see https://jenkins.apgsga.ch/configure

Hide password for dev artifactory user

---

vars/patchfunctions.groovy

The restart mechanism now saves the state of PatchConfig into Patch*.json file of the a Patch newly also before the execution of a Stage. In case of a failure of the Pipeline the target redo State is taken from PatchConfig: targetToState. 
This makes any db query for the state and targetToState of a Patch unnecessary.

Restart with saved toState

---

src/main/jenkins/server/clone/reinstallPatchAfterClonePipeline.groovy
vars/patchDeployment.groovy
vars/patchfunctions.groovy

The problem: 
The field installationTarget was used in "conflicting" ways
As Installation Target for OnDemandPipeline from the UI 
Internally as single reference from PatchConfig for the currentTarget being processed. 
With the redo, which saves the PatchConfig State before and after a Stage, this could lead to fact , that the installationTarget is overwritten from the Prod Pipeline.
Solution -> The single Reference in PatchConfig for the currentTarget being processed is renamed to currentTarget.

JAVA8MIG-504 onDemand Pipeline installed on wrong target

---

src/main/jenkins/server/patchProdPipeline.groovy
src/test/groovy/testPhases.groovy
src/test/resources/TargetSystemMappings.json

Very small change to patchProdPipeline.groovy. Basically retrieving keySet of the targetSystemMap, removing 'Entwicklung'  and iterating over the list instead of the hardcoded List of values. 
See file compore. 
This means no additional field and / or  format change  of /etc/opt/apg-patch-common/TargetSystemMappings.json is necessary. 
If ok , as soon as merge, additional phases can be added.

JAVA8MIG-480

---

build.gradle
gradle.properties
src/test/groovy/testPhases.groovy
src/test/resources/TargetSystemMappings.json
vars/patchfunctions.groovy

Suggested changes to support node Labels:
1. TargetSystemMappings.json an additional attribute with a list of serviceName and 
`...
"nodes": [
{
"label": "jadas-t",
"serviceName": "jadas"
}
],
...
`
2.  provide a groovy function to retrieve a nodeLabel for a given serviceName
`def nodeLabelFor(serviceName, nodes) `
in /jenkins-patch-scripts/vars/patchfunctions.groovy
I updated TargetSystemMappings.json on jenkins.apgsga.ch accordingly. 
The additional json seems backward compatible

Extend TargetSystemMappings with Node Labels For Target

---

vars/patchDeployment.groovy
vars/patchfunctions.groovy

I'll merge it immediately, it serves only as documentation/information purpose. The aim is to retrieve the "node label" where jadas will have to be installed, and assign this value to the patchConfig. For now, until JAVA8MIG-577 will be done, we're only echoing the information.

Getting node label where top install Jadas Service

---

vars/patchfunctions.groovy

Important decision: the stage(....) wrapper stays also for onDemand Pipeline, although it doesn't provide much value, except the uniform declarative invocation style of our stages.
In the stage(...)  wrapper, we check if the "logical" Targetname , like "Entwicklung" , "Informatiktest" etc is a existing name in Targetsystemmappings. If not like with "OnDemand" the saving of the state of patchConfig is skipped.

JAVA8MIG-735 OnDemand Pipeline überschreibt persistenten Redo Status

---

vars/patchfunctions.groovy

tested on Jenkins-t.apgsga.ch with patch 6180
- no time-out is shown any more on approval message
- still works with the normal workflow

1.1.x.java8 mig 722

---

src/main/jenkins/server/clone/onClonePipeline.groovy

JSON file with list of patch to be reinstalled needs to have distinguished name for each status (informatiktest, anwendertest, ...)

jhe-cm-176 / distinguished patchToBeReinstall file names

---

src/main/jenkins/server/clone/onClonePipeline.groovy
vars/patchDeployment.groovy
vars/patchfunctions.groovy

The node where to install Jadas Middletier is fetched dynamically based on information coming from targetBean.
The node is now retrieved only when we need it -> at deployment time.
This pull request is ready for feedback, but I would wait until CM-176 will be in production before merging it. If we merge it right now, it might not be easy to determine what will have to me backport on PROD for CM-176 (CM-176 should go in production on 16.04.2019).
Also if we wait before merging, it will be easier to test this one and CM-176 without having undesired side-effects.

java8mig-736 / Refactor Installation Node Selection

---

src/main/jenkins/server/clone/onClonePipeline.groovy

It seems to come from the following bug: https://issues.jenkins-ci.org/browse/JENKINS-43758
None of the suggested workaround in the ticket works for us, or at least their description is not 100% clear.
However, from what I tested, reading the Job parameter from the "env" variable instead of the "params" seem to do it.
This is a very minor correction, I could do some successful tests on jenkins-t. If it has any undesired side-effect, one can very quickly revert it.

cm-184 / Jenkins Pipeline onClonemaster.light verliert Parameter Defaults

---

vars/patchfunctions.groovy

temporary solution to re-enable original installation sequence of scripts for different it21 schema accounts until a "real" packaging is introduced for db objects, see ticket cm-216

1.1.x cm 216

---

vars/patchDeployment.groovy

Download from release Repo should work correctly again.
See also https://jira.apgsga.ch/browse/ARCH-94

ARCH-94 / ZIP-DIST Repository not needed anymore

---

src/main/jenkins/server/clone/onClonePipeline.groovy
src/main/jenkins/server/patchOnDemandPipeline.groovy
src/main/jenkins/server/patchProdPipeline.groovy
vars/patchDeployment.groovy
vars/patchfunctions.groovy

InstallOldStyle can lead to wrong installation order when a patch goes into production. The step needs to be part of the "installLock".

CM-225 / Patch Produktion-Installation Reihenfolge falsch?

---

vars/patchfunctions.groovy

When encountering a db-objects merge conflict at the end of patch, we want to overwrite the content of the prod branch with the content coming from patch tag.

CM-262 / CVS Merge of Patch-Tag to prod Branch does not overwrite
