- vars/patchDeployment.groovy
- vars/patchfunctions.groovy
This one goes together with https://github.com/apgsga-it/piper/pull/20.
We need to manage the "@P" version set after having clone a target.
> Java8mig353 support clone process

- src/main/jenkins/server/patchDownloadPipeline.groovy
- src/main/jenkins/server/patchProdPipeline.groovy
- vars/patchfunctions.groovy
The changes for supporting the "patching" of Libraries , which are not compiled with the Patch Pipeline. 
All other necessary changes (ui , piper, it21-ui-bundle) are already active and have been tested.
> Changes in Pipeline for Library Support

- src/main/jenkins/server/clone/onClonePipeline.groovy
- vars/patchfunctions.groovy
Adaptation which go together with: https://github.com/apgsga-it/piper/pull/40
> Calling apsrevcli for Revision tasks

- vars/patchfunctions.groovy
@apgsga-jhe  Pull request for your information
I will merge immediately
> Maven localRepo on Node Basis

- src/main/jenkins/server/patchProdPipeline.groovy
- src/main/jenkins/server/patchbuilder.groovy
First iteration Restart Pipeline: 
I basically just added the Parameter to support the  restart, nothing else. 
I will merge fast, test and make new branch with implementing the logic.
> First Iteration Restart Pipeline

- vars/patchfunctions.groovy
Adopted the call to comply with https://issues.jenkins-ci.org/browse/JENKINS-26133 and to use the apsdbcli. 
@apgsga-jhe  you will see this after my merge ;-)
> Refactored apscli for notification to apsdbcli

- src/main/jenkins/server/patchProdPipeline.groovy
- vars/patchfunctions.groovy
Implements the Restart Logic in the Pipeline. 
@apgsga-jhe FYI i will merge and start testing
For diffing use the skip Whitespace option
> Restart Logic

- vars/patchfunctions.groovy
@chhex : JFYI, I'll merge it immediately.
> removed all function related with -lpr or -spr

- vars/patchfunctions.groovy
As discussed in https://jira.apgsga.ch/browse/JAVA8MIG-236
> Lock for Co it21-ui-bundle

- vars/patchDeployment.groovy
- vars/patchfunctions.groovy
Keep 10 GUI folders.
correct dependency.
> Keep 10 GUI folder

- src/main/jenkins/server/patchOnDemandPipeline.groovy
- src/main/jenkins/server/patchProdPipeline.groovy
- vars/patchDeployment.groovy
- vars/patchfunctions.groovy
Aligned patchOnDemandPipeline.groovy to patchProdPipeline.groovy in terms of  stage closure.
> JAVA8MIG-448 Align Download Pipeline to current PatchPipeline in terms of stage closure

- build.gradle
- src/main/jenkins/server/clone/reinstallPatchAfterClonePipeline.groovy
- vars/patchDeployment.groovy
- vars/patchfunctions.groovy
What's definitely missing is retrieving the node name from TargetSystemMapping.
Probably also need to be discussed: what should the version of the RPM be?
... But otherwise, this pull request should be enough to go forward I believe.
> JAVA8MIG-578 - First set of modification to introduce yum deployment

- src/main/jenkins/server/clone/reinstallPatchAfterClonePipeline.groovy
- vars/patchDeployment.groovy
- vars/patchfunctions.groovy
> JAVA8MIG-703 onDemand Pipeline mit eigenem Entwickler Branch

- src/main/jenkins/server/clone/reinstallPatchAfterClonePipeline.groovy
- src/main/jenkins/server/patchOnDemandPipeline.groovy
- vars/patchDeployment.groovy
- vars/patchfunctions.groovy
Merge last changes into current production branch (Jenkins env variable called GITHUB_JENKINS_VERSION). 
BE CAREFUL: This pull request needs to be merged only when we'll be ready with the upgrade. Once merged, it's immediately used into production for all new pipeline jobs.
> Last changes into production branch

- vars/patchfunctions.groovy
Additional bracket for negation of condition in changed line
> JAVA8MIG-742 apscli --redo causes failure on "recovered" pipeline job by jumping approval step

- src/main/jenkins/server/clone/onClonePipeline.groovy
- src/main/jenkins/server/patchOnDemandPipeline.groovy
- vars/patchDeployment.groovy
- vars/patchfunctions.groovy
Could you have a quick look before I merge? 
If OK, I'll then also backport on Prod branch. As soon as backported, it will be productive. Probably it will also require a "script approval" from Jenkins GUI (no big deal).
> java8mig-736 / Refactor Installation Node Selection - second version

- src/main/jenkins/server/clone/onClonePipeline.groovy
- vars/patchfunctions.groovy
Not 100% sure this will work, but should basically not be more complicated than that.
Maybe you have a first feedback?
> java8mig732 / log patch steps in a separated JSON file

- src/main/jenkins/server/clone/onClonePipeline.groovy
- vars/patchfunctions.groovy
Workaround for delivery to master.light until JAVA8MIG-753 is implemented
> 1.1.x.arch 9

- vars/patchDeployment.groovy
A required Maven "settings.xml" file has also been created on both "apg-jdv-e-001" and "apg-jdv-p-001".
It has been tested on jenkins-t with Patch 6511. To see the output, look for "Downloading GUI-ZIP with following command" string into following outputs:
- https://jenkins-t.apgsga.ch/view/Patches/job/Patch6511OnDemand/12/consoleFull
- https://jenkins-t.apgsga.ch/view/Patches/job/Patch6511/4/consoleFull
> Arch-95 / maven cmd for zip download

- vars/patchfunctions.groovy
Der Title des Tickets ist eigentlich falsch, das passiert nicht während Clean-up, sondern während Patch Ablauf.
Wie im Ticket geschrieben, ganz einfach Anpassungen um den "Return-Value" zu loggen ...
Es wurde auf jenkins-t richtig getestet ...
> CM-264 / Jenkins Clean-Up Artifactory FAILED

- vars/patchDeployment.groovy
- vars/patchfunctions.groovy
Pull request done mostly for documentation purpose, it will be merged during week of 08.06. What has change:
- Old installation-GUI part done via windows Node has been removed. This will now be done only via SSH.
- A retry has been implemented for calls where Artifactory is involved. This is a workaround in order to deal with the situation where Artifactory is not available.
> CM-297 / Netzwerk Probleme mit Artifactory

- vars/patchDeployment.groovy
- vars/patchfunctions.groovy
@apgsga-uge : Ich bin noch am testen auf jenkins-t/CHEI211 .... aber wenn du schon Feedbacks hast, es ist natürlich wilkommen.
> CM-255 / Build (Compile, Assemble, Publish) sollen nur für Komponenten gemacht werden die wirklich geliefert werden sollen
